# Generated by Django 5.0.1 on 2024-02-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('school_principal', models.CharField(max_length=100)),
            ],
        ),
    ]
