# Generated by Django 4.2.7 on 2024-01-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='cemail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='cpassw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='passw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='semail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
